services:

  postgres:
    image: postgres:15
    container_name: aq_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: delhi_aq
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
    networks:
      - air_quality_net

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    container_name: aq_mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://postgres:root@postgres/delhi_aq
      --default-artifact-root /mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - air_quality_net
    restart: unless-stopped

  dagster-webserver:
    build: .
    container_name: aq_dagster_webserver
    command: dagster-webserver -h 0.0.0.0 -p 3000 -w dagster_pipeline/workspace.yaml
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - .:/app
      - dagster_home:/root/.dagster
    depends_on:
      - postgres
      - mlflow
    networks:
      - air_quality_net
    restart: unless-stopped

  dagster-daemon:
    build: .
    container_name: aq_dagster_daemon
    command: dagster-daemon run -w dagster_pipeline/workspace.yaml
    env_file: .env
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - .:/app
      - dagster_home:/root/.dagster
    depends_on:
      - postgres
      - mlflow
    networks:
      - air_quality_net
    restart: unless-stopped

  api:
    build: .
    container_name: aq_api
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_MODEL_URI: models:/DelhiAirQualityModel/Production
    depends_on:
      - mlflow
    networks:
      - air_quality_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.2
    container_name: aq_grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres
    networks:
      - air_quality_net
    restart: unless-stopped

volumes:
  postgres_data:
  mlflow_artifacts:
  dagster_home:
  grafana_data:

networks:
  air_quality_net:
    driver: bridge
